basePath: /api/v1
definitions:
  conf.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  conf.ResponseError:
    properties:
      code:
        type: integer
      err:
        type: string
      msg:
        type: string
    type: object
  model.OrderReq:
    properties:
      amount:
        type: number
      notify_url:
        type: string
      order_id:
        type: string
      pid:
        type: integer
      redirect_url:
        type: string
      signature:
        type: string
      trade_type:
        type: string
    type: object
host: localhost:2900
info:
  contact: {}
  description: DDpay https://github.com/zkeai/DDPay
  title: DDPay API
  version: 1.0.0
paths:
  /order/create-transaction:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户登录提交参数
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/model.OrderReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/conf.Response'
        "400":
          description: 参数错误
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 创建订单
      tags:
      - order
  /order/status:
    get:
      parameters:
      - description: 订单key
        in: query
        name: order
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/conf.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/conf.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/conf.ResponseError'
      summary: 获取当前订单状态
      tags:
      - order
swagger: "2.0"
